### ISSUE TITLE
public readVarint(InputStream in)

### ISSUE THREAD

**Issue by pepoospina** [ipld/java-cid#12]
Cannot downgrade visibility of method from public `readVariant` in current Multihash version

```
private static long readVarint(InputStream in) throws IOException {
```

**Comment by odisseus** [comment]
That method is [available](https://github.com/multiformats/java-multihash/blob/0eb305c02c7778abbb6c0379bea24fe553817f04/src/main/java/io/ipfs/multihash/Multihash.java#L267) as a public method in the latest version of [java-multihash](https://github.com/multiformats/java-multihash). I think it's going to be removed from this library.
