### ISSUE TITLE
version == 1, cid tostring base32 encode

### ISSUE THREAD

**Issue by jc0803kevin** [ipld/java-cid#19]
version == 1, cid tostring base32 encode

![image](https://user-images.githubusercontent.com/16516973/133190742-36ccfad0-3856-45ca-bc78-3039ccc8f87c.png)

**Comment by odisseus** [comment]
Can you describe the problem in more detail?

**Comment by jc0803kevin** [comment]
When cid tostring, the encoding format is wrong, the screenshot above is the go language source code

![image](https://user-images.githubusercontent.com/16516973/133546242-c313824d-c012-4f7f-845e-ebb8fa009d68.png)

**Comment by ianopolous** [comment]
Thanks! I've updated this.
