### ISSUE TITLE
cid mismatch

### ISSUE THREAD

**Issue by shichangzhi** [ipld/java-cid#21]
I use Java-CID and go-cid(version: 0, code: 0x70, hash: sha2_256), and I got the cid which is Qmb3muUVhutaHn23f19LRqgqv81X28tf3GXjkryetAHfFu, but if I use "ipfs add XXX", I got "QmeFnGJ5EauGBBS6Y6kVNguAuPUZZ4tqntF85D8J8XcxRS".
Is there anything wrong with the parameters?

**Comment by vmx** [comment]
If you use "ipfs add", then the file is chunked into smaller pieces and a Merkle tree is built. This leads to a hash that is not the same as if you hash just the raw bytes of a file. For more information see https://docs.ipfs.io/concepts/hashing/#content-identifiers-are-not-file-hashes.

**Comment by shichangzhi** [comment]
> If you use "ipfs add", then the file is chunked into smaller pieces and a Merkle tree is built. This leads to a hash that is not the same as if you hash just the raw bytes of a file. For more information see https://docs.ipfs.io/concepts/hashing/#content-identifiers-are-not-file-hashes.

Get it. thx
