### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by magwas** [ipld/java-cid#3]
I am trying to compile it using the master from multihash.

The first line of the constructor have problems, as Multihash have only a (byte[]) and a (Type,byte[])
constructor. Is changing the offending line to 'super(hash.toBytes());' kosher?

    public Cid(long version, Codec codec, Multihash hash) {
        super(hash);
        this.version = version;
        this.codec = codec;
    }

**Comment by tdiesler** [comment]
This might be out of date
